app:
  log_file: "./avatar.log"
  log_level: info
  port: 8080
  print_request_body: true
  metric_port: 9090

database:
  default:
    driver: mysql
    # 优先使用 DSN，如果没有则组合 host/user/password/dbname
    dsn: ""
    hosts:
      write: "127.0.0.1:3306"
#      reads:
#        - "127.0.0.1:3306"
#        - "127.0.0.1:3306"
#    user: "{{ env MYSQL_USER }}"           # 可以使用 viper env override
#    password: "{{ env MYSQL_PASS }}"
    user: "root"           # 可以使用 viper env override
    password: "xxxxxxxx"
    dbname: "xxxxxxxxx"
    params:
      # 尽量不要用大写字母，因为使用Viper解析时会默认把所有的key都转成小写
      parseTime: "true"
      loc: "Local"
      charset: "utf8mb4"
    pool:
      max_open_conns: 50
      max_idle_conns: 10
      conn_max_lifetime_min: 30
    health:
      ping_timeout_ms: 500
      ping_retries: 3
    read_write_split: true

#  analytics:
#    driver: mysql
#    dsn: "analytics_user:pwd@tcp(127.0.0.1:3306)/analytics?parseTime=true"
#    pool:
#      max_open_conns: 10
#      max_idle_conns: 2

